use crate::project::{ProjectContext, ProjectKind};

pub async fn scene(name: String, ctx: ProjectContext) -> anyhow::Result<()> {
    let dir = match ctx.kind {
        ProjectKind::EngineDev => ctx.project_root.join("examples"),
        ProjectKind::UserProject => ctx.project_root.join("scenes"),
    };
    std::fs::create_dir_all(&dir)?;

    let filename = if name.ends_with(".jl") {
        name.clone()
    } else {
        format!("{name}.jl")
    };
    let path = dir.join(&filename);

    if path.exists() {
        anyhow::bail!("File already exists: {}", path.display());
    }

    let scene_name = name.trim_end_matches(".jl");
    let content = generate_scene_template(scene_name);
    std::fs::write(&path, content)?;
    println!("Created scene: {}", path.display());
    Ok(())
}

fn generate_scene_template(name: &str) -> String {
    format!(
        r#"# {name} scene
# Generated by orcli

using OpenReality

reset_entity_counter!()
reset_component_stores!()

s = scene([
    # Player with FPS controls (WASD + mouse look)
    create_player(position=Vec3d(0, 1.7, 5)),

    # Directional light (sun)
    entity([
        DirectionalLightComponent(
            direction=Vec3f(0.3, -1.0, -0.5),
            intensity=2.0f0
        )
    ]),

    # Floor
    entity([
        plane_mesh(width=20.0f0, depth=20.0f0),
        MaterialComponent(
            color=RGB{{Float32}}(0.5, 0.5, 0.5),
            metallic=0.0f0,
            roughness=0.9f0
        ),
        transform(),
        ColliderComponent(shape=AABBShape(Vec3f(10.0, 0.01, 10.0)), offset=Vec3f(0, -0.01, 0)),
        RigidBodyComponent(body_type=BODY_STATIC)
    ]),

    # A cube to get started
    entity([
        cube_mesh(),
        MaterialComponent(
            color=RGB{{Float32}}(0.2, 0.6, 0.9),
            metallic=0.3f0,
            roughness=0.4f0
        ),
        transform(position=Vec3d(0, 0.5, 0)),
        ColliderComponent(shape=AABBShape(Vec3f(0.5, 0.5, 0.5))),
        RigidBodyComponent(body_type=BODY_STATIC)
    ])
])

@info "Scene created with $(entity_count(s)) entities"
render(s)
"#
    )
}
